#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/gpt_oss/modular_gpt_oss.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_gpt_oss.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
import time
from dataclasses import dataclass
import inspect
from typing import Callable, Dict, List, Optional, Union

import torch
from torch import nn
from torch.nn import functional as F

from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations.hub_kernels import use_kernel_forward_from_hub
from ...masking_utils import create_causal_mask, create_sliding_window_causal_mask
from ...modeling_layers import (
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from ...modeling_outputs import MoeCausalLMOutputWithPast, MoeModelOutputWithPast
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.deprecation import deprecate_kwarg
from ...utils.generic import OutputRecorder, check_model_inputs
from .configuration_gpt_oss import GptOssConfig


@use_kernel_forward_from_hub("RMSNorm")
def _runtime_get(obj, key, default=None):
    if obj is None:
        return default
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _runtime_flag(obj, key, default=False):
    value = _runtime_get(obj, key, default)
    return bool(value)


def _aggregate_controller_logprobs(record_dict):
    if not record_dict:
        return None
    total = None
    for value in record_dict.values():
        if value is None:
            continue
        tensor = value
        if isinstance(value, dict):
            switch_lp = value.get("switch_logprobs")
            selection_lp = value.get("selection_logprobs")
            if switch_lp is None or selection_lp is None:
                raise TypeError(
                    "controller logprob record must include switch_logprobs and selection_logprobs tensors"
                )
            tensor = switch_lp + selection_lp
        total = tensor if total is None else total + tensor
    return total


def _safe_logprob(probs: torch.Tensor) -> torch.Tensor:
    eps = torch.finfo(probs.dtype).tiny
    return torch.log(probs.clamp(min=eps))


def _safe_log1m(probs: torch.Tensor) -> torch.Tensor:
    eps = torch.finfo(probs.dtype).tiny
    return torch.log1p(-probs.clamp(min=eps, max=1 - eps))


def _plackett_luce_sample(
    logits: torch.Tensor, k: int, generator: Optional[torch.Generator] = None
) -> tuple[torch.Tensor, torch.Tensor]:
    if k <= 0:
        raise ValueError("`k` must be positive for Plackett-Luce sampling.")
    batch_size, num_candidates = logits.shape
    
    # Clamp logits to prevent numerical issues (avoid Inf after exp)
    # Using ±50 as reasonable bounds for logits before softmax
    remaining = logits.clamp(min=-50.0, max=50.0).clone()
    
    selected: list[torch.Tensor] = []
    total_logprob = torch.zeros(batch_size, device=logits.device, dtype=logits.dtype)
    eps = torch.finfo(logits.dtype).tiny
    
    for _ in range(k):
        probs = torch.nn.functional.softmax(remaining, dim=-1)
        
        # Safety check: replace NaN/Inf with uniform distribution
        bad_probs = ~torch.isfinite(probs).all(dim=-1)
        if bad_probs.any():
            # Count valid (non -inf) positions
            valid_mask = remaining > float("-inf")
            num_valid = valid_mask.sum(dim=-1, keepdim=True).clamp(min=1)
            uniform = valid_mask.float() / num_valid
            probs = torch.where(bad_probs.unsqueeze(-1), uniform, probs)
        
        # Ensure probabilities are valid (non-negative, sum to 1)
        probs = probs.clamp(min=eps)
        probs = probs / probs.sum(dim=-1, keepdim=True)
        
        if generator is None:
            idx = torch.multinomial(probs, num_samples=1, replacement=False)
        else:
            idx = torch.multinomial(probs, num_samples=1, replacement=False, generator=generator)
        gathered = torch.gather(probs, 1, idx).clamp(min=eps)
        total_logprob += gathered.log().squeeze(-1)
        remaining.scatter_(1, idx, float("-inf"))
        selected.append(idx.squeeze(-1))
    return torch.stack(selected, dim=-1), total_logprob


def _plackett_luce_logprob(
    logits: torch.Tensor,
    selections: torch.Tensor,
) -> torch.Tensor:
    """
    Compute the log probability of `selections` under a Plackett-Luce distribution parametrized by `logits`.
    The `selections` tensor should contain -1 for positions where no selection happened (e.g. no switch).
    """
    batch_size, k = selections.shape
    # Clamp logits to prevent numerical issues
    remaining = logits.clamp(min=-50.0, max=50.0).clone()
    total_logprob = torch.zeros(batch_size, device=logits.device, dtype=logits.dtype)
    for step in range(k):
        step_indices = selections[:, step]
        active = step_indices >= 0
        if not torch.any(active):
            continue
        current_remaining = remaining[active]
        log_probs = torch.nn.functional.log_softmax(current_remaining, dim=-1)
        # Handle potential NaN in log_probs (replace with uniform log prob as fallback)
        if not torch.isfinite(log_probs).all():
            num_valid = (current_remaining > float("-inf")).sum(dim=-1, keepdim=True).clamp(min=1)
            uniform_log_prob = -torch.log(num_valid.float())
            log_probs = torch.where(torch.isfinite(log_probs), log_probs, uniform_log_prob)
        gathered = torch.gather(log_probs, 1, step_indices[active].unsqueeze(-1))
        total_logprob[active] += gathered.squeeze(-1)
        remaining[active].scatter_(1, step_indices[active].unsqueeze(-1), float("-inf"))
    return total_logprob


def _indices_to_mask(indices: torch.Tensor, num_cols: int) -> torch.Tensor:
    mask = torch.zeros(indices.shape[0], num_cols, dtype=torch.bool, device=indices.device)
    mask.scatter_(1, indices, True)
    return mask


@dataclass
class GptOssControllerLayerState:
    allowed_mask: torch.Tensor
    hidden_state: torch.Tensor  # Canonical RNN hidden state (not output logits)


class GptOssRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        GptOssRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return (self.weight * hidden_states).to(input_dtype)  # main diff with Llama

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class GptOssExperts(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.intermediate_size = config.intermediate_size
        self.num_experts = config.num_local_experts
        self.hidden_size = config.hidden_size
        self.expert_dim = self.intermediate_size
        self.gate_up_proj = nn.Parameter(torch.empty(self.num_experts, self.hidden_size, 2 * self.expert_dim))
        self.gate_up_proj_bias = nn.Parameter(torch.empty(self.num_experts, 2 * self.expert_dim))
        self.down_proj = nn.Parameter(torch.empty((self.num_experts, self.expert_dim, self.hidden_size)))
        self.down_proj_bias = nn.Parameter(torch.empty(self.num_experts, self.hidden_size))
        self.alpha = 1.702
        self.limit = 7.0

    def forward(self, hidden_states: torch.Tensor, router_indices=None, routing_weights=None) -> torch.Tensor:
        """
        When training it is more efficient to just loop over the experts and compute the output for each expert
        as otherwise the memory would explode.

        For inference we can sacrifice some memory and compute the output for all experts at once. By repeating the inputs.

        Args:
            hidden_states (torch.Tensor): (batch_size, seq_len, hidden_size)
            selected_experts (torch.Tensor): (batch_size * token_num, top_k)
            routing_weights (torch.Tensor): (batch_size * token_num, num_experts)
        Returns:
            torch.Tensor
        """
        batch_size = hidden_states.shape[0]
        hidden_states = hidden_states.reshape(-1, self.hidden_size)  # (num_tokens, hidden_size)
        num_experts = routing_weights.shape[1]
        if hidden_states.device.type == "cpu" or self.training:
            next_states = torch.zeros_like(hidden_states, dtype=hidden_states.dtype, device=hidden_states.device)
            with torch.no_grad():
                expert_mask = torch.nn.functional.one_hot(
                    router_indices, num_classes=num_experts + 1
                )  # masking is also a class
                expert_mask = expert_mask.permute(2, 1, 0)
                # we sum on the top_k and on the sequence length to get which experts
                # are hit this time around
                expert_hit = torch.greater(expert_mask.sum(dim=(-1, -2)), 0).nonzero()
            for expert_idx in expert_hit[:]:
                # expert_idx only have 1 element, so we can use scale for fast indexing
                expert_idx = expert_idx[0]
                # skip masking index
                if expert_idx == num_experts:
                    continue
                with torch.no_grad():
                    _, token_idx = torch.where(expert_mask[expert_idx])
                current_state = hidden_states[token_idx]
                gate_up = current_state @ self.gate_up_proj[expert_idx] + self.gate_up_proj_bias[expert_idx]
                gate, up = gate_up[..., ::2], gate_up[..., 1::2]
                gate = gate.clamp(min=None, max=self.limit)
                up = up.clamp(min=-self.limit, max=self.limit)
                glu = gate * torch.sigmoid(gate * self.alpha)
                gated_output = (up + 1) * glu
                out = gated_output @ self.down_proj[expert_idx] + self.down_proj_bias[expert_idx]
                weighted_output = out * routing_weights[token_idx, expert_idx, None]
                next_states.index_add_(0, token_idx, weighted_output.to(hidden_states.dtype))
            next_states = next_states.view(batch_size, -1, self.hidden_size)
        else:
            hidden_states = hidden_states.repeat(num_experts, 1)
            hidden_states = hidden_states.view(num_experts, -1, self.hidden_size)
            gate_up = torch.bmm(hidden_states, self.gate_up_proj) + self.gate_up_proj_bias[..., None, :]
            gate, up = gate_up[..., ::2], gate_up[..., 1::2]
            gate = gate.clamp(min=None, max=self.limit)
            up = up.clamp(min=-self.limit, max=self.limit)
            glu = gate * torch.sigmoid(gate * self.alpha)
            next_states = torch.bmm(((up + 1) * glu), self.down_proj)
            next_states = next_states + self.down_proj_bias[..., None, :]
            next_states = next_states.view(num_experts, batch_size, -1, self.hidden_size)
            next_states = next_states * routing_weights.transpose(0, 1).view(num_experts, batch_size, -1)[..., None]
            next_states = next_states.sum(dim=0)
        return next_states


class GptOssTopKRouter(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.top_k = config.num_experts_per_tok
        self.num_experts = config.num_local_experts
        self.hidden_dim = config.hidden_size
        self.weight = nn.Parameter(torch.empty(self.num_experts, self.hidden_dim))
        self.bias = nn.Parameter(torch.empty(self.num_experts))

    def compute_router_logits(self, hidden_states: torch.Tensor) -> torch.Tensor:
        hidden_states = hidden_states.reshape(-1, self.hidden_dim)
        return F.linear(hidden_states, self.weight, self.bias)

    def forward(self, hidden_states):
        router_logits = self.compute_router_logits(hidden_states)  # (seq_len, num_experts)
        self._last_router_logits = router_logits
        router_top_value, router_indices = torch.topk(router_logits, self.top_k, dim=-1)  # (seq_len, top_k)
        router_top_value = torch.nn.functional.softmax(router_top_value, dim=1, dtype=router_top_value.dtype)
        router_scores = torch.zeros_like(router_logits).scatter_(1, router_indices, router_top_value)
        return router_scores, router_indices


class GptOssController(nn.Module):
    """
    Canonical RNN Controller with separate hidden state.
    
    Architecture:
        h_t = GRU(h_{t-1}, x_t)  where x_t = [router_softmax, expert_mask]
        switch_logits = switch_head(h_t)
        candidate_logits = expert_head(h_t)
        value = value_head(h_t)
    
    The hidden state h carries temporal information across tokens,
    enabling the controller to make informed decisions based on history.
    All outputs (switch, expert selection, value) come from the same
    hidden representation, ensuring consistent state estimation.
    """
    def __init__(self, config: GptOssConfig):
        super().__init__()
        self.num_experts = config.num_local_experts
        self.hidden_dim = config.controller_hidden_dim
        self.dropout = config.controller_dropout
        
        # Input: [router_softmax, expert_mask] = 2 * num_experts
        self.input_dim = 2 * self.num_experts
        
        # GRU cell for RNN transition (single recurrent layer)
        # Replaces the two separate 2-layer MLPs with a canonical RNN structure
        self.gru_cell = nn.GRUCell(self.input_dim, self.hidden_dim)
        
        # Output heads (all from hidden state h)
        # These are simple linear projections from the rich hidden representation
        self.switch_head = nn.Linear(self.hidden_dim, 1)
        self.expert_head = nn.Linear(self.hidden_dim, self.num_experts)
        self.value_head = nn.Linear(self.hidden_dim, 1)
        
        # Optional dropout on hidden state
        self.hidden_dropout = nn.Dropout(self.dropout) if self.dropout else None
        
        # NOTE: dtype is set by from_pretrained() after __init__, so we cannot set it here.
        # Controller parameters are converted to float32 in controller_trainer.py after model loading.

    def forward(
        self, 
        x_t: torch.Tensor, 
        h_prev: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        One step of the canonical RNN controller.
        
        Args:
            x_t: [router_softmax, expert_mask], shape (batch, 2*num_experts)
            h_prev: hidden state from previous step, shape (batch, hidden_dim)
            
        Returns:
            h_t: new hidden state, shape (batch, hidden_dim)
            switch_logits: shape (batch,)
            candidate_logits: shape (batch, num_experts)
            value: shape (batch,)
        """
        # Cast inputs to parameter dtype (handles bfloat16 input with float32 params)
        param_dtype = next(self.gru_cell.parameters()).dtype
        x_t = x_t.to(dtype=param_dtype)
        h_prev = h_prev.to(dtype=param_dtype)
        
        # GRU transition: h_t = GRU(h_{t-1}, x_t)
        h_t = self.gru_cell(x_t, h_prev)
        
        # Optional dropout on hidden state
        if self.hidden_dropout is not None and self.training:
            h_t = self.hidden_dropout(h_t)
        
        # Output heads (all from the same hidden state)
        switch_logits = self.switch_head(h_t).squeeze(-1)
        candidate_logits = self.expert_head(h_t)
        value = self.value_head(h_t).squeeze(-1)
        
        return h_t, switch_logits, candidate_logits, value
    
    def init_hidden(self, batch_size: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        """Initialize hidden state to zeros."""
        return torch.zeros(batch_size, self.hidden_dim, device=device, dtype=dtype)


@use_kernel_forward_from_hub("MegaBlocksMoeMLP")
class GptOssMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.router = GptOssTopKRouter(config)
        self.experts = GptOssExperts(config)
        self.controller_enabled = getattr(config, "controller_enabled", False)
        self.controller_allowed_experts = getattr(config, "controller_allowed_experts", self.router.top_k)
        self.controller_switch_threshold = getattr(config, "controller_switch_threshold", 0.5)
        self.controller_sampling_temperature = max(getattr(config, "controller_sampling_temperature", 1.0), 1e-5)
        self.layer_idx: Optional[int] = None
        if self.controller_enabled:
            self.controller = GptOssController(config)
        else:
            self.controller = None

    def _route_experts(
        self,
        hidden_states: torch.Tensor,
        router_indices: torch.Tensor,
        routing_weights: torch.Tensor,
        routing_data: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Call experts with a signature-compatible argument set across different expert kernels.
        Prefers explicit kwargs when available; falls back through positional signatures.
        """
        if routing_data is None:
            routing_data = routing_weights
        try:
            sig = inspect.signature(self.experts.forward)
            param_names = [p.name for p in sig.parameters.values()][1:]  # skip 'self'
        except Exception:
            param_names = []

        kwargs = {}
        if "routing_data" in param_names:
            kwargs["routing_data"] = routing_data
        if "router_indices" in param_names:
            kwargs["router_indices"] = router_indices
        if "routing_weights" in param_names:
            kwargs["routing_weights"] = routing_weights
        elif "router_scores" in param_names:
            kwargs["router_scores"] = routing_weights
        if "gather_idx" in param_names and routing_data is not None:
            kwargs["gather_idx"] = router_indices
        if "scatter_idx" in param_names and routing_data is not None:
            kwargs["scatter_idx"] = router_indices

        # Try kwargs path
        try:
            if kwargs:
                return self.experts(hidden_states, **kwargs)
        except TypeError:
            pass

        # Positional variants in order of likelihood
        positional_variants = [
            (routing_data, router_indices, router_indices),
            (routing_weights, router_indices),
            (routing_weights,),
            tuple(),
        ]
        for variant in positional_variants:
            try:
                return self.experts(hidden_states, *variant)
            except TypeError:
                continue
        raise TypeError("Unable to call experts with available routing data")

    def _mask_router_logits(self, logits: torch.Tensor, allowed_mask: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        mask_value = torch.finfo(logits.dtype).min
        masked_logits = logits.masked_fill(~allowed_mask, mask_value)
        top_values, top_indices = torch.topk(masked_logits, self.router.top_k, dim=-1)
        top_probs = torch.nn.functional.softmax(top_values, dim=-1, dtype=top_values.dtype)
        router_scores = torch.zeros_like(logits).scatter_(1, top_indices, top_probs)
        return router_scores, top_indices

    def _apply_controller_step(
        self,
        router_softmax: torch.Tensor,  # Already softmaxed router logits
        allowed_mask: Optional[torch.Tensor],
        hidden_state: Optional[torch.Tensor],  # RNN hidden state (not output logits)
        runtime_config,
        replay_payload: Optional[Dict[str, torch.Tensor]] = None,
    ) -> tuple[
        torch.Tensor,  # switch_decision
        torch.Tensor,  # allowed_mask
        torch.Tensor,  # hidden_state (for next step)
        torch.Tensor,  # switch_logprob
        torch.Tensor,  # selection_logprob
        torch.Tensor,  # selected_indices
        torch.Tensor,  # value
        torch.Tensor,  # controller_input (for recording: [router_softmax, expert_mask])
    ]:
        """
        Apply one step of the canonical RNN controller.
        
        Canonical RNN architecture:
            h_t = GRU(h_{t-1}, x_t)  where x_t = [router_softmax, expert_mask]
            switch_logits, candidate_logits, value = heads(h_t)
        
        The hidden state h carries temporal information, enabling better
        value estimation and more informed decisions.
        """
        batch_size, num_experts = router_softmax.shape
        
        # Initialize allowed_mask if None
        if allowed_mask is None:
            allowed_mask = torch.zeros(batch_size, num_experts, dtype=torch.bool, device=router_softmax.device)
        
        # Initialize hidden state if None
        if hidden_state is None:
            hidden_state = self.controller.init_hidden(batch_size, router_softmax.device, router_softmax.dtype)
        
        # Prepare input x_t = [router_softmax, expert_mask]
        expert_mask_float = allowed_mask.to(dtype=router_softmax.dtype)
        x_t = torch.cat([router_softmax, expert_mask_float], dim=-1)  # [batch, 2*num_experts]
        
        # Forward through canonical RNN controller
        h_t, switch_logits, candidate_logits, value = self.controller(x_t, hidden_state)
        
        # Clamp outputs to prevent numerical issues (NaN in softmax/multinomial)
        switch_logits = switch_logits.clamp(-20, 20)
        candidate_logits = candidate_logits.clamp(-20, 20)
        value = value.clamp(-100, 100)
        
        if self.controller_sampling_temperature != 1.0:
            candidate_logits = candidate_logits / self.controller_sampling_temperature
        
        switch_probs = torch.sigmoid(switch_logits)
        sampling_mode = _runtime_flag(runtime_config, "sampling", False) and replay_payload is None
        generator = _runtime_get(runtime_config, "generator", None)
        
        # Determine switch decision
        if replay_payload is not None:
            switch_decision = replay_payload["switches"].to(dtype=torch.bool, device=router_softmax.device)
        elif sampling_mode:
            bernoulli_p = switch_probs.clamp(min=1e-6, max=1 - 1e-6)
            rand = torch.rand(
                switch_probs.shape,
                device=switch_probs.device,
                dtype=switch_probs.dtype,
                generator=generator,
            )
            switch_decision = rand < bernoulli_p
        else:
            switch_decision = switch_probs >= self.controller_switch_threshold

        # Compute switch log probability
        switch_logprob = torch.where(
            switch_decision,
            _safe_logprob(switch_probs),
            _safe_log1m(switch_probs),
        )

        # Expert selection - ALWAYS sample/compute for ALL samples (not just switch=True)
        # This ensures balanced log_prob magnitudes between switch and no-switch actions
        # Use float32 for log probabilities (controller outputs are float32 for numerical stability)
        active = torch.nonzero(switch_decision).squeeze(-1)

        if replay_payload is not None:
            # During replay: use recorded indices for ALL samples
            selected_indices = replay_payload["selected_indices"].to(dtype=torch.long, device=router_softmax.device)
            # Compute log_prob for ALL samples (not just active)
            selection_logprob = _plackett_luce_logprob(candidate_logits, selected_indices)
        elif sampling_mode:
            # During sampling: sample for ALL samples
            selected_indices, selection_logprob = _plackett_luce_sample(
                candidate_logits,
                self.controller_allowed_experts,
                generator=generator,
            )
        else:
            # Greedy mode: topk for ALL samples
            selected_indices = torch.topk(candidate_logits, self.controller_allowed_experts, dim=-1).indices
            selection_logprob = torch.zeros(batch_size, device=router_softmax.device, dtype=torch.float32)

        # Update allowed_mask ONLY for tokens where switch=1
        # (selected_indices are recorded for all, but only used when switch=1)
        if active.numel() > 0:
            allowed_mask = allowed_mask.clone()
            allowed_mask[active] = False
            allowed_mask.scatter_(1, selected_indices[active], True)

        return (
            switch_decision,
            allowed_mask,
            h_t,  # Pass hidden state to next step (canonical RNN)
            switch_logprob,
            selection_logprob,
            selected_indices,
            value,
            x_t,  # Controller input for recording (simplified: just x_t)
        )


    def forward(
        self,
        hidden_states,
        controller_state: Optional[GptOssControllerLayerState] = None,
        controller_runtime=None,
    ):
        if not self.controller_enabled:
            router_scores, router_indices = self.router(hidden_states)
            routed_out = self.experts(hidden_states, router_indices=router_indices, routing_weights=router_scores)
            return routed_out, router_scores, controller_state

        batch_size, seq_len, _ = hidden_states.shape
        router_logits = self.router.compute_router_logits(hidden_states).view(batch_size, seq_len, -1)
        allowed_mask = controller_state.allowed_mask if controller_state is not None else None
        hidden_state = controller_state.hidden_state if controller_state is not None else None
        
        # Traces for recording (canonical RNN architecture)
        switch_trace = []
        switch_logprob_trace = []
        selection_logprob_trace = []
        selected_indices_trace = []
        value_trace = []
        controller_input_trace = []  # x_t = [router_softmax, expert_mask]
        router_logits_trace = []

        layer_idx = getattr(self, "layer_idx", None)
        record_actions = _runtime_get(controller_runtime, "record_actions", None)
        replay_actions = _runtime_get(controller_runtime, "replay_actions", None)
        layer_replay = None
        if replay_actions is not None and layer_idx is not None:
            layer_replay = replay_actions.get(layer_idx)

        record_logprobs = _runtime_get(controller_runtime, "record_logprobs", None)

        # Determine if this is the very first token (no prior controller state)
        # Only the first token (t=0) uses router top-k to initialize
        # All subsequent tokens (t>0, whether prefill or generation) use normal controller operation
        is_first_forward = controller_state is None
        
        for token_idx in range(seq_len):
            token_logits = router_logits[:, token_idx, :]
            # Convert router logits to softmax for controller input (consistent with training)
            # Clamp to avoid numerical issues (same as training)
            router_softmax = torch.softmax(token_logits.float().clamp(-50, 50), dim=-1).to(token_logits.dtype)
            is_first_token = token_idx == 0 and is_first_forward
            use_replay = layer_replay is not None
            
            if is_first_token:
                # t=0: Initialize with router top-k, no switch decision
                # Initialize hidden state and allowed_mask
                allowed_mask = torch.zeros_like(token_logits, dtype=torch.bool)
                top_allowed = torch.topk(token_logits, self.controller_allowed_experts, dim=-1).indices
                allowed_mask.scatter_(1, top_allowed, True)
                hidden_state = self.controller.init_hidden(token_logits.shape[0], token_logits.device, token_logits.dtype)
                switch_decision = torch.zeros(token_logits.shape[0], dtype=torch.bool, device=token_logits.device)
                # Use float32 for log probabilities and value (controller outputs are float32 for numerical stability)
                switch_logprob = torch.zeros(token_logits.shape[0], dtype=torch.float32, device=token_logits.device)
                selection_logprob = torch.zeros(token_logits.shape[0], dtype=torch.float32, device=token_logits.device)
                selected_indices = torch.full(
                    (token_logits.shape[0], self.controller_allowed_experts),
                    -1,
                    dtype=torch.long,
                    device=token_logits.device,
                )
                value = torch.zeros(token_logits.shape[0], dtype=torch.float32, device=token_logits.device)
                # Controller input for recording: x_t = [router_softmax, expert_mask]
                controller_input = torch.cat([router_softmax, allowed_mask.to(dtype=token_logits.dtype)], dim=-1)
                
                # Run controller to initialize hidden state for t=1
                # This ensures t=0's hidden state captures the initial context
                x_t = controller_input
                hidden_state, _, _, _ = self.controller(x_t, hidden_state)
            else:
                # t>0: Normal controller operation (both prefill and generation)
                # Controller can decide to switch experts based on learned policy
                replay_payload = None
                if layer_replay is not None:
                    replay_payload = {
                        "switches": layer_replay["switches"][:, token_idx],
                        "selected_indices": layer_replay["selected_indices"][:, token_idx],
                    }
                
                (
                    switch_decision,
                    allowed_mask,
                    hidden_state,  # Canonical RNN: hidden state
                    switch_logprob,
                    selection_logprob,
                    selected_indices,
                    value,
                    controller_input,  # x_t = [router_softmax, expert_mask]
                ) = self._apply_controller_step(
                    router_softmax,  # Pass softmax instead of raw logits
                    allowed_mask,
                    hidden_state,  # Pass hidden state
                    controller_runtime,
                    replay_payload=replay_payload,
                )
            
            # Record traces
            router_logits_trace.append(token_logits.detach())
            switch_trace.append(switch_decision)
            switch_logprob_trace.append(switch_logprob)
            selection_logprob_trace.append(selection_logprob)
            selected_indices_trace.append(selected_indices)
            value_trace.append(value)
            controller_input_trace.append(controller_input.detach())
            
            # Apply mask to router logits
            masked_logits = token_logits.masked_fill(~allowed_mask, torch.finfo(token_logits.dtype).min)
            router_logits[:, token_idx, :] = masked_logits

        masked_logits_matrix = router_logits.reshape(batch_size * seq_len, -1)
        top_values, top_indices = torch.topk(masked_logits_matrix, self.router.top_k, dim=-1)
        top_probs = torch.nn.functional.softmax(top_values, dim=-1, dtype=top_values.dtype)
        dense_router_scores = masked_logits_matrix.new_zeros(masked_logits_matrix.shape)
        dense_router_scores.scatter_(1, top_indices, top_probs)
        stacked_scores = dense_router_scores.view(batch_size, seq_len, -1)
        stacked_indices = top_indices.view(batch_size, seq_len, -1)
        routed_out = self._route_experts(
            hidden_states,
            stacked_indices.view(-1, self.router.top_k),
            stacked_scores.view(-1, self.router.num_experts),
            routing_data=stacked_scores.view(-1, self.router.num_experts),
        )
        next_state = GptOssControllerLayerState(
            allowed_mask=allowed_mask,
            hidden_state=hidden_state,  # Canonical RNN: pass hidden state
        )

        if record_actions is not None and layer_idx is not None:
            new_record = {
                "switches": torch.stack(switch_trace, dim=1),
                "switch_logprobs": torch.stack(switch_logprob_trace, dim=1),
                "selection_logprobs": torch.stack(selection_logprob_trace, dim=1),
                "selected_indices": torch.stack(selected_indices_trace, dim=1),
                "values": torch.stack(value_trace, dim=1),
                "router_logits": torch.stack(router_logits_trace, dim=1),
                "controller_inputs": torch.stack(controller_input_trace, dim=1),  # x_t = [router_softmax, expert_mask]
            }
            if layer_idx in record_actions:
                prev_record = record_actions[layer_idx]
                new_record = {
                    key: torch.cat([prev_record[key], value], dim=1) for key, value in new_record.items()
                }
            record_actions[layer_idx] = {
                key: value.detach() for key, value in new_record.items()
            }

        if record_logprobs is not None and layer_idx is not None:
            record_logprobs[layer_idx] = {
                "switch_logprobs": torch.stack(switch_logprob_trace, dim=1),
                "selection_logprobs": torch.stack(selection_logprob_trace, dim=1),
            }

        return routed_out, stacked_scores.view(-1, self.router.num_experts), next_state

    # Explicit controller path callable to bypass any kernel-forward replacement
    def forward_controller(
        self,
        hidden_states,
        controller_state: Optional[GptOssControllerLayerState] = None,
        controller_runtime=None,
    ):
        # Just delegate to forward - they should behave the same
        return self.forward(hidden_states, controller_state, controller_runtime)

class GptOssRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: GptOssConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and isinstance(config.rope_scaling, dict):
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = freqs
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(x.dtype), sin.to(x.dtype)


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def _apply_rotary_emb(
    x: torch.Tensor,
    cos: torch.Tensor,
    sin: torch.Tensor,
) -> torch.Tensor:
    first_half, second_half = torch.chunk(x, 2, dim=-1)
    first_ = first_half * cos - second_half * sin
    second_ = second_half * cos + first_half * sin
    return torch.cat((first_, second_), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = _apply_rotary_emb(q, cos, sin)
    k_embed = _apply_rotary_emb(k, cos, sin)
    return q_embed, k_embed


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)
    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    sinks = module.sinks.reshape(1, -1, 1, 1).expand(query.shape[0], -1, query.shape[-2], -1)
    combined_logits = torch.cat([attn_weights, sinks], dim=-1)

    # This was not in the original implementation and slightly affect results; it prevents overflow in BF16/FP16
    # when training with bsz>1 we clamp max values.

    combined_logits = combined_logits - combined_logits.max(dim=-1, keepdim=True).values
    probs = F.softmax(combined_logits, dim=-1, dtype=combined_logits.dtype)
    scores = probs[..., :-1]  # we drop the sink here
    attn_weights = nn.functional.dropout(scores, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()
    return attn_output, attn_weights


class GptOssAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: GptOssConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True
        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        self.sliding_window = config.sliding_window if config.layer_types[layer_idx] == "sliding_attention" else None
        self.sinks = nn.Parameter(torch.empty(config.num_attention_heads))

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_values: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            cache_kwargs = {"cache_position": cache_position}
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx, cache_kwargs)

        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            sliding_window=self.sliding_window,
            s_aux=self.sinks,  # diff with Llama
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class GptOssDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: GptOssConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size
        self.self_attn = GptOssAttention(config=config, layer_idx=layer_idx)
        self.mlp = GptOssMLP(config)
        self.mlp.layer_idx = layer_idx
        self.input_layernorm = GptOssRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = GptOssRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        controller_state: Optional[GptOssControllerLayerState] = None,
        controller_runtime=None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, Optional[GptOssControllerLayerState]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        # Self Attention
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        controller_enabled = getattr(self.mlp, "controller_enabled", False)
        experts = getattr(self.mlp, "experts", None)
        experts_cls_name = experts.__class__.__name__ if experts is not None else ""
        uses_mxfp4 = experts_cls_name == "Mxfp4GptOssExperts"
        if controller_enabled and not uses_mxfp4:
            hidden_states, _, next_controller_state = self.mlp.forward_controller(
                hidden_states,
                controller_state=controller_state,
                controller_runtime=controller_runtime,
            )  # diff with llama: router scores
        else:
            hidden_states, _, next_controller_state = self.mlp(
                hidden_states,
                controller_state=controller_state,
                controller_runtime=controller_runtime,
            )  # diff with llama: router scores
        hidden_states = residual + hidden_states
        return hidden_states, next_controller_state


@auto_docstring
class GptOssPreTrainedModel(PreTrainedModel):
    config: GptOssConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["GptOssDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = False
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "router_logits": OutputRecorder(GptOssTopKRouter, index=0),
        "hidden_states": GptOssDecoderLayer,
        "attentions": GptOssAttention,
    }
    _keep_in_fp32_modules = ["post_attention_layernorm", "input_layernorm", "norm", "controller"]
    _supports_flash_attention = False
    _supports_flex_attention = False

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, GptOssController):
            # Canonical RNN Controller initialization:
            # - GRU cell: Xavier for input-hidden, orthogonal for hidden-hidden
            # - Output heads: Xavier with zero bias
            # NOTE: Some init functions (orthogonal) don't support bfloat16,
            # so we do init in float32 and convert back to original dtype
            hidden_dim = module.hidden_dim
            input_dim = module.input_dim
            
            # GRU cell has weight_ih (input-hidden) and weight_hh (hidden-hidden)
            # Each contains gates: reset (r), update (z), new (n) stacked as [r, z, n]
            gru = module.gru_cell
            with torch.no_grad():
                # Save original dtype for conversion back
                orig_dtype = gru.weight_ih.dtype
                
                # Input-hidden weights: Xavier initialization
                # Shape: [3 * hidden_dim, input_dim]
                weight_ih_f32 = gru.weight_ih.data.float()
                nn.init.xavier_uniform_(weight_ih_f32)
                gru.weight_ih.data.copy_(weight_ih_f32.to(orig_dtype))
                
                # Hidden-hidden weights: Orthogonal initialization (better for RNNs)
                # Shape: [3 * hidden_dim, hidden_dim]
                # Split into 3 parts for r, z, n gates and apply orthogonal to each
                weight_hh_f32 = gru.weight_hh.data.float()
                for i in range(3):
                    start = i * hidden_dim
                    end = (i + 1) * hidden_dim
                    nn.init.orthogonal_(weight_hh_f32[start:end])
                gru.weight_hh.data.copy_(weight_hh_f32.to(orig_dtype))
                
                # Biases: zero
                if gru.bias_ih is not None:
                    gru.bias_ih.data.zero_()
                if gru.bias_hh is not None:
                    gru.bias_hh.data.zero_()
            
            # Output heads: Xavier with zero bias
            # Also need float32 for some edge cases
            with torch.no_grad():
                for head in [module.switch_head, module.expert_head, module.value_head]:
                    orig_dtype = head.weight.dtype
                    weight_f32 = head.weight.data.float()
                    nn.init.xavier_uniform_(weight_f32)
                    head.weight.data.copy_(weight_f32.to(orig_dtype))
                    head.bias.data.zero_()
        elif isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Parameter):
            module.data.normal_(mean=0.0, std=std)
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, GptOssRMSNorm):
            module.weight.data.fill_(1.0)
        elif isinstance(module, GptOssExperts):
            module.gate_up_proj.data.normal_(mean=0.0, std=std)
            module.gate_up_proj_bias.data.zero_()
            module.down_proj.data.normal_(mean=0.0, std=std)
            module.down_proj_bias.data.zero_()
        elif isinstance(module, GptOssAttention):
            module.sinks.data.normal_(mean=0.0, std=std)
        elif isinstance(module, GptOssTopKRouter):
            module.weight.data.normal_(mean=0.0, std=std)
            module.bias.data.normal_(mean=0.0, std=std)

    def prepare_inputs_for_generation(
        self,
        input_ids,
        past_key_values=None,
        attention_mask=None,
        controller_states=None,
        controller_runtime=None,
        **kwargs,
    ):
        model_inputs = super().prepare_inputs_for_generation(
            input_ids,
            past_key_values=past_key_values,
            attention_mask=attention_mask,
            **kwargs,
        )
        if controller_states is not None:
            model_inputs["controller_states"] = controller_states
        if controller_runtime is not None:
            model_inputs["controller_runtime"] = controller_runtime
        return model_inputs

    def _update_model_kwargs_for_generation(
        self,
        outputs,
        model_kwargs,
        is_encoder_decoder=False,
        num_new_tokens=1,
    ):
        model_kwargs = super()._update_model_kwargs_for_generation(
            outputs,
            model_kwargs,
            is_encoder_decoder=is_encoder_decoder,
            num_new_tokens=num_new_tokens,
        )
        if hasattr(outputs, "controller_states"):
            model_kwargs["controller_states"] = outputs.controller_states
        return model_kwargs


@auto_docstring
class GptOssModel(GptOssPreTrainedModel):
    _no_split_modules = ["GptOssDecoderLayer"]

    def __init__(self, config: GptOssConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [GptOssDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = GptOssRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = GptOssRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        controller_states: Optional[List[Optional[GptOssControllerLayerState]]] = None,
        controller_runtime=None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> MoeModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )
        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # It may already have been prepared by e.g. `generate`
        if not isinstance(causal_mask_mapping := attention_mask, dict):
            mask_kwargs = {
                "config": self.config,
                "input_embeds": inputs_embeds,
                "attention_mask": attention_mask,
                "cache_position": cache_position,
                "past_key_values": past_key_values,
            }
            causal_mask_mapping = {
                "full_attention": create_causal_mask(**mask_kwargs),
                "sliding_attention": create_sliding_window_causal_mask(**mask_kwargs),
            }

        hidden_states = inputs_embeds
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        if controller_states is None:
            controller_states = [None] * len(self.layers)
        next_controller_states: list[Optional[GptOssControllerLayerState]] = []

        for layer_idx, decoder_layer in enumerate(self.layers):
            layer_controller_state = controller_states[layer_idx] if controller_states else None
            hidden_states, updated_controller_state = decoder_layer(
                hidden_states,
                attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                controller_state=layer_controller_state,
                controller_runtime=controller_runtime,
                **kwargs,
            )
            next_controller_states.append(updated_controller_state)
        hidden_states = self.norm(hidden_states)
        outputs = MoeModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )
        outputs.controller_states = next_controller_states
        controller_logprob = None
        if controller_runtime is not None:
            record_logprobs = _runtime_get(controller_runtime, "record_logprobs", None)
            controller_logprob = _aggregate_controller_logprobs(record_logprobs)
        # Suppress verbose aggregation logs
        outputs.controller_logprobs = controller_logprob
        return outputs


def load_balancing_loss_func(
    gate_logits: Union[torch.Tensor, tuple[torch.Tensor], None],
    num_experts: Optional[int] = None,
    top_k=2,
    attention_mask: Optional[torch.Tensor] = None,
) -> Union[torch.Tensor, int]:
    r"""
    Computes auxiliary load balancing loss as in Switch Transformer - implemented in Pytorch.

    See Switch Transformer (https://huggingface.co/papers/2101.03961) for more details. This function implements the loss
    function presented in equations (4) - (6) of the paper. It aims at penalizing cases where the routing between
    experts is too unbalanced.

    Args:
        gate_logits:
            Logits from the `gate`, should be a tuple of model.config.num_hidden_layers tensors of
            shape [batch_size X sequence_length, num_experts].
        num_experts:
            Number of experts
        top_k:
            The number of experts to route per-token, can be also interpreted as the `top-k` routing
            parameter.
        attention_mask (`torch.Tensor`, *optional*):
            The attention_mask used in forward function
            shape [batch_size X sequence_length] if not None.

    Returns:
        The auxiliary loss.
    """
    if gate_logits is None or not isinstance(gate_logits, tuple):
        return 0

    if isinstance(gate_logits, tuple):
        compute_device = gate_logits[0].device
        concatenated_gate_logits = torch.cat([layer_gate.to(compute_device) for layer_gate in gate_logits], dim=0)

    routing_weights = torch.nn.functional.softmax(concatenated_gate_logits, dim=-1)

    _, selected_experts = torch.topk(routing_weights, top_k, dim=-1)

    expert_mask = torch.nn.functional.one_hot(selected_experts, num_experts)

    if attention_mask is None:
        # Compute the percentage of tokens routed to each experts
        tokens_per_expert = torch.mean(expert_mask.float(), dim=0)

        # Compute the average probability of routing to these experts
        router_prob_per_expert = torch.mean(routing_weights, dim=0)
    else:
        batch_size, sequence_length = attention_mask.shape
        num_hidden_layers = concatenated_gate_logits.shape[0] // (batch_size * sequence_length)

        # Compute the mask that masks all padding tokens as 0 with the same shape of expert_mask
        expert_attention_mask = (
            attention_mask[None, :, :, None, None]
            .expand((num_hidden_layers, batch_size, sequence_length, top_k, num_experts))
            .reshape(-1, top_k, num_experts)
            .to(compute_device)
        )

        # Compute the percentage of tokens routed to each experts
        tokens_per_expert = torch.sum(expert_mask.float() * expert_attention_mask, dim=0) / torch.sum(
            expert_attention_mask, dim=0
        )

        # Compute the mask that masks all padding tokens as 0 with the same shape of tokens_per_expert
        router_per_expert_attention_mask = (
            attention_mask[None, :, :, None]
            .expand((num_hidden_layers, batch_size, sequence_length, num_experts))
            .reshape(-1, num_experts)
            .to(compute_device)
        )

        # Compute the average probability of routing to these experts
        router_prob_per_expert = torch.sum(routing_weights * router_per_expert_attention_mask, dim=0) / torch.sum(
            router_per_expert_attention_mask, dim=0
        )

    overall_loss = torch.sum(tokens_per_expert * router_prob_per_expert.unsqueeze(0))
    return overall_loss * num_experts


@auto_docstring
class GptOssForCausalLM(GptOssPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = GptOssModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.router_aux_loss_coef = config.router_aux_loss_coef
        self.num_experts = config.num_local_experts
        self.num_experts_per_tok = config.num_experts_per_tok

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_router_logits: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> MoeCausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        Example:

        ```python
        >>> from transformers import AutoTokenizer, GptOssForCausalLM

        >>> model = GptOssForCausalLM.from_pretrained("mistralai/GptOss-8x7B-v0.1")
        >>> tokenizer = AutoTokenizer.from_pretrained("mistralai/GptOss-8x7B-v0.1")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""

        output_router_logits = (
            output_router_logits if output_router_logits is not None else self.config.output_router_logits
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: MoeModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_router_logits=output_router_logits,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits, labels, self.vocab_size, **kwargs)

        aux_loss = None
        if output_router_logits:
            aux_loss = load_balancing_loss_func(
                outputs.router_logits,
                self.num_experts,
                self.num_experts_per_tok,
                attention_mask,
            )
            if labels is not None:
                loss += self.router_aux_loss_coef * aux_loss.to(loss.device)  # make sure to reside in the same device

        result = MoeCausalLMOutputWithPast(
            loss=loss,
            aux_loss=aux_loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            router_logits=outputs.router_logits,
            controller_logprobs=outputs.controller_logprobs,
        )
        # Preserve controller_states for generation (not a standard field, set dynamically)
        if hasattr(outputs, "controller_states"):
            result.controller_states = outputs.controller_states
        return result


class GptOssForSequenceClassification(GenericForSequenceClassification, GptOssPreTrainedModel):
    pass


class GptOssForTokenClassification(GenericForTokenClassification, GptOssPreTrainedModel):
    pass


__all__ = [
    "GptOssForCausalLM",
    "GptOssForSequenceClassification",
    "GptOssForTokenClassification",
    "GptOssModel",
    "GptOssPreTrainedModel",
]
